FROM python:3.12-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir fastapi uvicorn joblib scikit-learn prometheus-client

CMD ["uvicorn", "src.serving.api:app", "--host", "0.0.0.0", "--port", "8000"]
